application: sandeep-koduri
version: v1-4
runtime: python27
api_version: 1
threadsafe: no

includes:

- sessions/app.yaml

handlers:



- url: /qa_admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /users/.*
  script: usersManagement.users.app

- url: .*
  script: fotoMashCore.main.app





libraries:
- name: webapp2
  version: "2.5.1"

- name: PIL
  version: latest


- name: django
  version: latest

- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
- name: jinja2
  version: "2.6"
- name: lxml
  version: '2.3'
  
  